#include <stdio.h>
#include <stdlib.h>
#include "piles.h"
#include "files.h"
int main(){

	NEUDPILE* tetepile=NULL;
	NEUDFILE* tetefile=NULL;
	int nombre;
	int tetepiletab=-1;
	int tetefiletab=-1;
	int queuefiletab=-1;

	printf("A-les piles (statiques et dynamiques)\n\n\n");
	printf("A1-les piles (dynamiques)\n");
	printf("1-effectuons les operations:\n\n");
	tetepile=depiler(tetepile);
	tetepile=depiler(tetepile);
	nombre=1;
	tetepile=enpiler(nombre,tetepile);
	afficher_pile(tetepile);
	nombre=2;
	tetepile=enpiler(nombre,tetepile);
	afficher_pile(tetepile);
	nombre=3;
	tetepile=enpiler(nombre,tetepile);
	afficher_pile(tetepile);
	tetepile=depiler(tetepile);
	afficher_pile(tetepile);
	nombre=4;
	tetepile=enpiler(nombre,tetepile);
	afficher_pile(tetepile);
	nombre=5;
	tetepile=enpiler(nombre,tetepile);
	afficher_pile(tetepile);
	tetepile=depiler(tetepile);
	afficher_pile(tetepile);
	nombre=6;
	tetepile=enpiler(nombre,tetepile);
	afficher_pile(tetepile);
	nombre=7;
	tetepile=enpiler(nombre,tetepile);
	afficher_pile(tetepile);
	nombre=8;
	tetepile=enpiler(nombre,tetepile);
	afficher_pile(tetepile);
	nombre=9;
	tetepile=enpiler(nombre,tetepile);
	afficher_pile(tetepile);
	nombre=10;
	tetepile=enpiler(nombre,tetepile);
	afficher_pile(tetepile);
	tetepile=depiler(tetepile);
	afficher_pile(tetepile);
	printf("2- au  sommet de la pile ? la fin on a: %d.\n",tetepile->entier);
	printf("3- depiler ne s'execute pas normalement 2 fois.\n");
	printf("4- enpiler ne s'execute pas normalement 0 fois.\n");
	
	printf("\n##############################################################################################################################################\n");
	printf("\nA1-les piles (statiques)\n\n");
	tetepiletab=depiler_tableau(tetepiletab);
	tetepiletab=depiler_tableau(tetepiletab);
	nombre=1;
	tetepiletab=enpiler_tableau(nombre,tetepiletab);
	afficher_pile_tableau(tetepiletab) ;
	nombre=2;
	tetepiletab=enpiler_tableau(nombre,tetepiletab);
	afficher_pile_tableau(tetepiletab) ;
	nombre=3;
	tetepiletab=enpiler_tableau(nombre,tetepiletab);
	afficher_pile_tableau(tetepiletab) ;
	tetepiletab=depiler_tableau(tetepiletab);
	afficher_pile_tableau(tetepiletab) ;
	nombre=4;
	tetepiletab=enpiler_tableau(nombre,tetepiletab);
	afficher_pile_tableau(tetepiletab) ;
	nombre=5;
	tetepiletab=enpiler_tableau(nombre,tetepiletab);
	afficher_pile_tableau(tetepiletab) ;
	tetepiletab=depiler_tableau(tetepiletab);
	afficher_pile_tableau(tetepiletab);
	nombre=6;
	tetepiletab=enpiler_tableau(nombre,tetepiletab);
	afficher_pile_tableau(tetepiletab) ;
	nombre=7;
	tetepiletab=enpiler_tableau(nombre,tetepiletab);
	afficher_pile_tableau(tetepiletab) ;
	nombre=8;
	tetepiletab=enpiler_tableau(nombre,tetepiletab);
	afficher_pile_tableau(tetepiletab) ;
	nombre=9;
	tetepiletab=enpiler_tableau(nombre,tetepiletab);
	afficher_pile_tableau(tetepiletab) ;
	nombre=10;
	tetepiletab=enpiler_tableau(nombre,tetepiletab);
	afficher_pile_tableau(tetepiletab) ;
	tetepiletab=depiler_tableau(tetepiletab);
	afficher_pile_tableau(tetepiletab) ;
	printf("2- au  sommet de la pile ? la fin on a: 6.\n");
	printf("3- depiler ne s'execute pas normalement 2 fois.\n");
	printf("4- empiler ne s'execute pas normalement 3 fois.\n");
	
	printf("\n##############################################################################################################################################\n");
	printf("B-les files (statiques et dynamiques)\n\n\n");
	printf("B1-les files (dynamiques)\n");
	printf("1-effectuons les operations:\n\n");
	
	tetefile=defiler(tetefile);
	tetefile=defiler(tetefile);
	nombre=1;
	tetefile=enfiler(nombre,tetefile);
	afficher_file(tetefile);
	nombre=2;
	tetefile=enfiler(nombre,tetefile);
	afficher_file(tetefile);
	nombre=3;
	tetefile=enfiler(nombre,tetefile);
	afficher_file(tetefile);
	tetefile=defiler(tetefile);
	afficher_file(tetefile);
	nombre=4;
	tetefile=enfiler(nombre,tetefile);
	afficher_file(tetefile);
	nombre=5;
	tetefile=enfiler(nombre,tetefile);
	afficher_file(tetefile);
	tetefile=defiler(tetefile);
	afficher_file(tetefile);
	nombre=6;
	tetefile=enfiler(nombre,tetefile);
	afficher_file(tetefile);
	nombre=7;
	tetefile=enfiler(nombre,tetefile);
	afficher_file(tetefile);
	nombre=8;
	tetefile=enfiler(nombre,tetefile);
	afficher_file(tetefile);
	nombre=9;
	tetefile=enfiler(nombre,tetefile);
	afficher_file(tetefile);
	nombre=10;
	tetefile=enfiler(nombre,tetefile);
	afficher_file(tetefile);
	tetefile=defiler(tetefile);
	afficher_file(tetefile);
	printf("2- au  sommet de la file  la fin on a: 4.\n");
	printf("3- en queue de  file  la fin on a: %d.\n",tetefile->entier);
	printf("4- defiler ne s'execute pas normalement 2 fois.\n");
	printf("5- enfiler ne s'execute normalement  0 fois.\n");
	
	printf("\n##############################################################################################################################################\n");
	printf("\nA1-les piles (statiques)\n\n");
	defiler_tableau(&tetefiletab, &queuefiletab);
	defiler_tableau(&tetefiletab, &queuefiletab);
	nombre=1;
	enfiler_tableau(&tetefiletab,&queuefiletab,nombre);
	afficher_file_tableau(tetefiletab,queuefiletab);
	nombre=2;
	enfiler_tableau(&tetefiletab,&queuefiletab,nombre);
	afficher_file_tableau(tetefiletab,queuefiletab);
	nombre=3;
	enfiler_tableau(&tetefiletab,&queuefiletab,nombre);
	afficher_file_tableau(tetefiletab,queuefiletab);
	defiler_tableau(&tetefiletab, &queuefiletab);
	afficher_file_tableau(tetefiletab,queuefiletab);
	nombre=4;
	enfiler_tableau(&tetefiletab,&queuefiletab,nombre);
	afficher_file_tableau(tetefiletab,queuefiletab);
	nombre=5;
	enfiler_tableau(&tetefiletab,&queuefiletab,nombre);
	afficher_file_tableau(tetefiletab,queuefiletab);
	defiler_tableau(&tetefiletab, &queuefiletab);
	afficher_file_tableau(tetefiletab,queuefiletab);
	nombre=6;
	enfiler_tableau(&tetefiletab,&queuefiletab,nombre);
	afficher_file_tableau(tetefiletab,queuefiletab);
	nombre=7;
	enfiler_tableau(&tetefiletab,&queuefiletab,nombre);
	afficher_file_tableau(tetefiletab,queuefiletab);
	nombre=8;
	enfiler_tableau(&tetefiletab,&queuefiletab,nombre);
	afficher_file_tableau(tetefiletab,queuefiletab);
	nombre=9;
	enfiler_tableau(&tetefiletab,&queuefiletab,nombre);
	afficher_file_tableau(tetefiletab,queuefiletab);
	nombre=10;
	enfiler_tableau(&tetefiletab,&queuefiletab,nombre);
	afficher_file_tableau(tetefiletab,queuefiletab);
	printf("2- au  sommet de la file  la fin on a: 3.\n");
	printf("3- en queue de  file  la fin on a: 7%d.\n",tetefile->entier);
	printf("4- defiler ne s'execute pas normalement 2 fois.\n");
	printf("5- enfiler ne s'execute normalement  3 fois.\n");
	printf("6- les indices de dubut et de fin dans la version statique ? la  fin sont: indide-debut=2 ,indice-fin=1.\n");
	return 0;
}
